language: java

before_install:
- openssl aes-256-cbc -K $encrypted_d4a7eb0181c9_key -iv $encrypted_d4a7eb0181c9_iv -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml

script: cd org.uqbar.project.wollok.releng/ && mvn clean install

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "dev" && cd ../org.uqbar.project.wollok.updatesite
  && mvn -DupdateSiteFolder=$TRAVIS_BRANCH -P uploadRepo install
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && cd ../org.uqbar.project.wollok.updatesite
  && mvn -DupdateSiteFolder=$TRAVIS_BRANCH -P uploadRepo,uploadProducts install

jdk:
- oraclejdk7

notifications:
  webhooks:
    urls:
    - env.GITTER_URL
    on_success: change
    on_failure: always
    on_start: false

cache:
  directories:
  - $HOME/.m2
