language: java

before_install:
- openssl aes-256-cbc -K $encrypted_d4a7eb0181c9_key -iv $encrypted_d4a7eb0181c9_iv -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml

script: 
- cd org.uqbar.project.wollok.releng/ 
- export PROFILES=normalProfile
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "dev" && export PROFILES="uploadRepo"
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "dev" && export PROFILES="uploadRepo,uploadProducts"
- echo "Running with profiles $PROFILES"
- mvn -DupdateSiteFolder=$TRAVIS_BRANCH clean install -P $PROFILES

jdk:
- oraclejdk7

notifications:
  webhooks:
    urls:
    - env.GITTER_URL
    on_success: change
    on_failure: always
    on_start: false

cache:
  directories:
  - $HOME/.m2
