# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Wollok
tagline:          'Objetos de este siglo'
description:      'Un lenguaje y entorno de aprendizaje de Programación Orientada a Objetos.'
url:              http://github.org/uqbar-project/wollok
image:            images/WollokLogo.png

author:
  name:           'Javier Fernandes'
  url:            https://ar.linkedin.com/in/javier-fernandes-0144414

#paginate:         5

# Custom vars
version:          3.1.0

github:
  repo:           http://github.org/uqbar-project/wollok

gems: 
  - jekyll-paginate
  - jekyll-watch
